
name: Mirror Repository                                                                                                      

on:                                                                                                                          
  push:                                                                                                                      
    branches:                                                                                                                
      - main            
  schedule:
    - cron:  '0 0 * * *'  # Runs every day at midnight
permissions:
  contents: write  # Grants write access to the repository content

jobs:                                                                                                                        
  mirror:                                                                                                                    
    runs-on: ubuntu-latest                                                                                                   

    steps:                                                                                                                   
      - name: Checkout repository                                                                                            
        uses: actions/checkout@v2                                                                                            

      - name: Configure Git                                                                                                  
        run: |                                                                                                               
          git config --global user.email "actions@github.com"                                                                
          git config --global user.name "GitHub Action"                                                                      

      - name: Add source repository as remote                                                                                
        run: |                                                                                                               
          git remote add source https://github.com/IERoboticsClub/club-website.git                                           

      - name: Fetch source repository                                                                                        
        run: |                                                                                                               
          git fetch source                                                                                                   

      - name: Merge source repository                                                                                        
        run: |                                                                                                               
          git checkout source/main -- . ':!.github/workflows'                                                                

      - name: Push changes                                                                                                   
        run: |                                                                                                               
          git add .                                                                                                          
          git commit -m 'Update from source repository'                                                                      
          git push origin main                                                                                               
